// <auto-generated />
namespace IdentityMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class allmodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(allmodel));
        
        string IMigrationMetadata.Id
        {
            get { return "202004020738483_allmodel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
